# Generated by Django 2.0.12 on 2021-01-27 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_auto_20210126_0518'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveTradingData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_value', models.DateTimeField(auto_now_add=True)),
                ('high_value', models.FloatField(blank=True, null=True)),
                ('low_value', models.FloatField(blank=True, null=True)),
                ('open_value', models.FloatField(blank=True, null=True)),
                ('close_value', models.FloatField(blank=True, null=True)),
                ('change_percent_value', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Data',
        ),
    ]
