# Generated by Django 2.0.12 on 2021-01-27 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_auto_20210127_0753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livetradingdata',
            name='change_percent_value',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='livetradingdata',
            name='close_value',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='livetradingdata',
            name='date_value',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='livetradingdata',
            name='high_value',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='livetradingdata',
            name='low_value',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='livetradingdata',
            name='open_value',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
