# Generated by Django 2.0.12 on 2021-01-27 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_auto_20210127_0828'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livetradingdata',
            name='date_value',
        ),
    ]
